from setuptools import setup, find_packages

setup(
    name="jianying_web",
    author="topfunplus",
    version="0.1",
    packages=find_packages(),
    install_requires=[
        "asgiref == 3.8.1",
        "certifi == 2025.4.26",
        "charset-normalizer == 3.4.2",
        "comtypes == 1.4.11",
        "Django == 4.2.7",
        "django-cors-headers == 4.3.1",
        "django-filter == 23.5",
        "djangorestframework == 3.14.0",
        "djangorestframework-simplejwt == 5.3.0",
        "greenlet == 3.2.2",
        "idna == 3.10",
        "imageio == 2.37.0",
        "mysqlclient == 2.2.7",
        "numpy == 2.2.6",
        "Pillow == 10.1.0",
        "PyJWT == 2.10.1",
        "pymediainfo == 7.0.1",
        "PyMySQL == 1.1.0",
        "python-dotenv == 1.0.0",
        "pytz == 2025.2",
        "requests == 2.31.0",
        "setuptools == 80.9.0",
        "SQLAlchemy == 2.0.41",
        "sqlparse == 0.5.3",
        "typing_extensions == 4.14.0",
        "tzdata == 2025.2",
        "uiautomation == 2.0.28",
        "urllib3 == 2.4.0",
        "whitenoise == 6.6.0",
    ],
)
